package com.example.model

import androidx.compose.ui.graphics.Color
import com.example.ui.theme.AccentCyan
import com.example.ui.theme.AccentPink
import com.example.ui.theme.AccentPurple

enum class ToolCategory(val displayName: String) {
    ALL("All"),
    CALCULATORS("Calculators"),
    GENERATORS("Generators"),
    MEDIA_TEXT("Media & Text"),
    UTILITIES("Utilities")
}

data class ToolItem(
    val id: String,
    val title: String,
    val category: ToolCategory,
    val categoryLabel: String,
    val iconName: String,
    val description: String,
    val metricLabel: String,
    val metricValue: String,
    val statusBadge: String,
    val tagText: String,
    val primaryColor: Color,
    val secondaryColor: Color
)

object ToolRepository {
    val tools = listOf(
        ToolItem(
            id = "age",
            title = "Age Calculator",
            category = ToolCategory.CALCULATORS,
            categoryLabel = "Calculator",
            iconName = "calendar_clock",
            description = "Calculate exact years, months, days lived, total hours, and next birthday countdown.",
            metricLabel = "Precision",
            metricValue = "Real-time sec",
            statusBadge = "Live Milestone",
            tagText = "v2.1 • Instant",
            primaryColor = AccentPurple,
            secondaryColor = AccentCyan
        ),
        ToolItem(
            id = "units",
            title = "Unit Converter",
            category = ToolCategory.CALCULATORS,
            categoryLabel = "Calculator",
            iconName = "sync_alt",
            description = "Real-time conversion across Length, Weight, Temperature, Area, and Volume metrics.",
            metricLabel = "Metrics",
            metricValue = "5 Domains",
            statusBadge = "Bidirectional",
            tagText = "SI / Imperial",
            primaryColor = AccentCyan,
            secondaryColor = AccentPurple
        ),
        ToolItem(
            id = "qr",
            title = "QR Code Generator",
            category = ToolCategory.GENERATORS,
            categoryLabel = "Generator",
            iconName = "qr_code_scanner",
            description = "Generate instant downloadable SVG & PNG QR matrices with custom foreground accents.",
            metricLabel = "Export",
            metricValue = "High-Res PNG",
            statusBadge = "Zero Tracking",
            tagText = "Custom Color",
            primaryColor = AccentPink,
            secondaryColor = AccentPurple
        ),
        ToolItem(
            id = "compressor",
            title = "Image Compressor",
            category = ToolCategory.MEDIA_TEXT,
            categoryLabel = "Media & Text",
            iconName = "photo_size_select_small",
            description = "In-browser client-side image optimizer with variable quality slider and byte reduction metrics.",
            metricLabel = "Engine",
            metricValue = "HTML5 Canvas",
            statusBadge = "Up to -85%",
            tagText = "No Server Upload",
            primaryColor = AccentPurple,
            secondaryColor = AccentCyan
        ),
        ToolItem(
            id = "password",
            title = "Password Generator",
            category = ToolCategory.GENERATORS,
            categoryLabel = "Generators",
            iconName = "key",
            description = "Cryptographically secure password foundry with length constraints and live bit entropy score.",
            metricLabel = "RNG",
            metricValue = "crypto.getRandom",
            statusBadge = "128-bit+",
            tagText = "Custom Rules",
            primaryColor = AccentCyan,
            secondaryColor = AccentPink
        ),
        ToolItem(
            id = "splitter",
            title = "Expense Splitter",
            category = ToolCategory.CALCULATORS,
            categoryLabel = "Calculators",
            iconName = "receipt_long",
            description = "Split dinner checks, calculate tip percentages, adjust party counts, and export individual tallies.",
            metricLabel = "Features",
            metricValue = "Tip + Even Split",
            statusBadge = "Quick Share",
            tagText = "Smart Rounding",
            primaryColor = AccentPurple,
            secondaryColor = AccentPink
        ),
        ToolItem(
            id = "palette",
            title = "Palette Generator",
            category = ToolCategory.GENERATORS,
            categoryLabel = "Generators",
            iconName = "palette",
            description = "Harmonious 5-color aesthetic palettes with lockable swatches, hex copy, and CSS variable export.",
            metricLabel = "Shortcut",
            metricValue = "Spacebar",
            statusBadge = "Export CSS",
            tagText = "Lockable Slugs",
            primaryColor = AccentPink,
            secondaryColor = AccentCyan
        ),
        ToolItem(
            id = "words",
            title = "Word Counter",
            category = ToolCategory.MEDIA_TEXT,
            categoryLabel = "Media & Text",
            iconName = "format_align_left",
            description = "Real-time word, character, sentence, paragraph counts, reading duration, and keyword distribution.",
            metricLabel = "Speed",
            metricValue = "220 wpm",
            statusBadge = "Live Frequency",
            tagText = "Keyword Density",
            primaryColor = AccentCyan,
            secondaryColor = AccentPurple
        ),
        ToolItem(
            id = "love",
            title = "Love Calculator",
            category = ToolCategory.CALCULATORS,
            categoryLabel = "Calculators",
            iconName = "favorite",
            description = "Fun cosmic compatibility scoring between names and zodiacs with relationship advice & share card.",
            metricLabel = "Algorithm",
            metricValue = "Cosmic Sync",
            statusBadge = "High Dopamine",
            tagText = "Instant Match",
            primaryColor = AccentPink,
            secondaryColor = AccentPurple
        ),
        ToolItem(
            id = "bg_remover",
            title = "Photo BG Remover",
            category = ToolCategory.MEDIA_TEXT,
            categoryLabel = "Media & Text",
            iconName = "auto_fix_high",
            description = "Client-side edge chrominance isolation & background replacement for portraits, products, and stickers.",
            metricLabel = "Privacy",
            metricValue = "Zero Upload",
            statusBadge = "100% Offline",
            tagText = "Edge Isolation",
            primaryColor = AccentCyan,
            secondaryColor = AccentPurple
        ),
        ToolItem(
            id = "captions",
            title = "Caption Generator",
            category = ToolCategory.GENERATORS,
            categoryLabel = "Generators",
            iconName = "auto_awesome",
            description = "Craft high-engagement viral captions, hooks, hashtags, and call-to-actions across Instagram, YouTube & TikTok.",
            metricLabel = "Reach",
            metricValue = "5 Platforms",
            statusBadge = "Viral Hooks",
            tagText = "Smart Tone",
            primaryColor = AccentPurple,
            secondaryColor = AccentPink
        ),
        ToolItem(
            id = "thumbnail",
            title = "Thumbnail Generator",
            category = ToolCategory.GENERATORS,
            categoryLabel = "Generators",
            iconName = "smart_display",
            description = "Render 16:9 ultra-high contrast YouTube thumbnails with customizable headlines, badges, and cyberpunk glow themes.",
            metricLabel = "Resolution",
            metricValue = "1280x720 HD",
            statusBadge = "Click Magnets",
            tagText = "YouTube 16:9",
            primaryColor = AccentPink,
            secondaryColor = AccentCyan
        ),
        ToolItem(
            id = "tweet_meme",
            title = "Fake Tweet & Meme Maker",
            category = ToolCategory.GENERATORS,
            categoryLabel = "Generators",
            iconName = "chat_bubble",
            description = "Design authentic verified X/Twitter screenshots, viral quotes, jokes, and dark/light meme cards.",
            metricLabel = "Format",
            metricValue = "Verified 𝕏",
            statusBadge = "Viral Meme",
            tagText = "Tweet Quote",
            primaryColor = AccentPurple,
            secondaryColor = AccentCyan
        ),
        ToolItem(
            id = "fancy_fonts",
            title = "Aesthetic Bio & Fonts",
            category = ToolCategory.MEDIA_TEXT,
            categoryLabel = "Media & Text",
            iconName = "text_fields",
            description = "Transform standard text into 10+ Gothic, Cursive, Small Caps, and Bubble Unicode styles for Instagram bio & captions.",
            metricLabel = "Styles",
            metricValue = "10+ Fonts",
            statusBadge = "Bio Ready",
            tagText = "Unicode Magic",
            primaryColor = AccentCyan,
            secondaryColor = AccentPurple
        ),
        ToolItem(
            id = "spin_wheel",
            title = "Spin Wheel Decision",
            category = ToolCategory.UTILITIES,
            categoryLabel = "Utilities",
            iconName = "casino",
            description = "Smooth rotating decision wheel of fortune with custom choices, random turns, and fun winner highlights.",
            metricLabel = "Physics",
            metricValue = "Smooth Spin",
            statusBadge = "Mystery Pick",
            tagText = "Toss & Wheel",
            primaryColor = AccentPink,
            secondaryColor = AccentPurple
        ),
        ToolItem(
            id = "reel_hooks",
            title = "Viral Reel & Hook AI",
            category = ToolCategory.GENERATORS,
            categoryLabel = "Generators",
            iconName = "play_arrow",
            description = "3-second pattern interrupts, curiosity gap hooks, and script frameworks for YouTube Shorts & Instagram Reels.",
            metricLabel = "Retention",
            metricValue = "0-3s Hooks",
            statusBadge = "High Reach",
            tagText = "Reels & Shorts",
            primaryColor = AccentPurple,
            secondaryColor = AccentPink
        ),
        ToolItem(
            id = "wallpaper",
            title = "Gradient Wallpaper Studio",
            category = ToolCategory.MEDIA_TEXT,
            categoryLabel = "Media & Text",
            iconName = "wallpaper",
            description = "Generate aesthetic 9:16 vertical mesh and neon gradients for mobile lockscreens with randomizer & hex export.",
            metricLabel = "Aspect",
            metricValue = "9:16 Mobile",
            statusBadge = "Aesthetic",
            tagText = "Lockscreen Art",
            primaryColor = AccentCyan,
            secondaryColor = AccentPink
        ),
        ToolItem(
            id = "aura",
            title = "Daily Aura & Vibe Reader",
            category = ToolCategory.UTILITIES,
            categoryLabel = "Utilities",
            iconName = "self_improvement",
            description = "Analyze daily vibe, creative energy score, and cosmic focus profile with ready-to-share story cards.",
            metricLabel = "Cosmic",
            metricValue = "Vibe Energy",
            statusBadge = "Daily Check",
            tagText = "Aura Card",
            primaryColor = AccentPink,
            secondaryColor = AccentPurple
        ),
        ToolItem(
            id = "ram_chat",
            title = "Ram AI Assistant",
            category = ToolCategory.UTILITIES,
            categoryLabel = "Utilities",
            iconName = "smart_toy",
            description = "Multi-turn Gemini AI assistant powered by gemini-3.5-flash to ask questions about features, tools, and creator advice.",
            metricLabel = "AI Engine",
            metricValue = "gemini-3.5-flash",
            statusBadge = "Gemini AI",
            tagText = "Chat Specialist",
            primaryColor = AccentPurple,
            secondaryColor = AccentCyan
        ),
        ToolItem(
            id = "bmi",
            title = "BMI Health & Ideal Weight",
            category = ToolCategory.CALCULATORS,
            categoryLabel = "Calculators",
            iconName = "fitness_center",
            description = "Calculate Body Mass Index, discover your healthy weight range, and get actionable fitness advice.",
            metricLabel = "Metric",
            metricValue = "WHO Standard",
            statusBadge = "Health Check",
            tagText = "Ideal Weight",
            primaryColor = AccentCyan,
            secondaryColor = AccentPurple
        ),
        ToolItem(
            id = "water",
            title = "Daily Water Hydration Tracker",
            category = ToolCategory.UTILITIES,
            categoryLabel = "Utilities",
            iconName = "local_drink",
            description = "Track daily hydration in milliliters and glasses with quick drink presets and completion motivation.",
            metricLabel = "Target",
            metricValue = "3000 ml",
            statusBadge = "Hydration",
            tagText = "Daily Habit",
            primaryColor = AccentCyan,
            secondaryColor = AccentPink
        ),
        ToolItem(
            id = "sleep",
            title = "Sleep Cycle & REM Calculator",
            category = ToolCategory.UTILITIES,
            categoryLabel = "Utilities",
            iconName = "bedtime",
            description = "Find the exact times to sleep or set your alarm based on natural 90-minute REM cycles to wake up refreshed.",
            metricLabel = "Cycles",
            metricValue = "90-min REM",
            statusBadge = "No Grogginess",
            tagText = "Optimal Rest",
            primaryColor = AccentPurple,
            secondaryColor = AccentCyan
        ),
        ToolItem(
            id = "pomodoro",
            title = "Pomodoro Focus Timer",
            category = ToolCategory.UTILITIES,
            categoryLabel = "Utilities",
            iconName = "timer",
            description = "25/5 interval productivity clock for deep focus, study sprints, and work sessions without burnout.",
            metricLabel = "Intervals",
            metricValue = "25m / 5m",
            statusBadge = "Deep Work",
            tagText = "Productivity",
            primaryColor = AccentPink,
            secondaryColor = AccentPurple
        )
    )
}
